### ISSUE TITLE
Trouble shoot issues with resize function and score function.

### ISSUE THREAD

**Issue by justinjames76** [microsoft/HealthyCountryAI#75]
Images not resizing when large number of images are added.

Can we deploy the function that adds the resized images to customvision.ai

Update Dec 18 2019 (Justin Perry)
Receiving the following error.  score regions function and it cancelled due to time out  Timeout value of 00:15:00 exceeded by function 'Functions.score_regions' (Id: '856f0ced-f538-48d9-9fa8-7d298f8f31fc'). Initiating cancellation.

When adding new photographs using the desktop app.  Photos are being uploaded correctly but most photos aren't being resized or scored and there is no logging data available to describe why it failed in the monitoring output.

**Comment by krisbock** [comment]
#24 This should have been fixed with the latest PR, adding the create_tiles function into the workflow.
